dist: xenial

language: python

matrix:
  include:
    - python: pypy3.5-7.0.0
    - python: pypy3.6-7.1.1
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - python -m pip install --upgrade pip setuptools
  - python -m pip install --upgrade codecov
  - python -m pip install --force-reinstall -r requirements.txt
  - python -m pip install --force-reinstall -r requirements-tests.txt

script:
  - pytest
  - python -m doctest README.md

after_success:
  - python -m codecov -f coverage.xml -X gcov

deploy:
  provider: pypi
  on:
    tags: true
    python: 3.5
  user: __token__
  password:
    secure: lKZ9dY9bQTlOv9QwiOTGLKU5KiXpBHyec5fQAGwh4W8vUYa5Bn6XZaHzDRQF6JyDNrO6DzrGF78b+kKWPvFr9kKReWlJKMzyh++tA2q765pG+RWl41OE5D349oF1fhBiooT3qdUV8P3vspv/PE9u/evPtpj1LGvHPjwW3m9mwtu9Fr5cM0XmrF4OYvIOGSF1MJn4xOL6pjA6RfOcxMu97oicrQ5CCf8arbAgg0asm6qMu/lvrp6s+6oRQDGx+b27H5wzWUMpLdX0oYZhAWwY1bofO41e/Z+Us/RilXTOkdGf0LIpJRzqsjxYd2L6c/tv3EKv1BtjBW4W2kEnDxKRYNzykCK8xdCF/PfFngfPQ+4nOv/a0RyxhCvxiW9oBtnSNjlRqXMoVJjxDiLRMbJSiD1SUMZspJHgcIlf6Hrwit4Bsiw9uUwkLKnJs66XAzju9zcEKGQYLeBWbq/Jz/noauBM9syDqdVnuYxfP4mxjGlZ83kxgRx356HjcshwZNmthxOk67KRnRw7h0ClynpuC8fzJt5o/LUfj7niwjSrUs+v4htNWLwiTlzD6OZPHZeHjCE00mNIwm7XKbCFpuIXGXhhj0DvSbHhsIzZuxUZsxfVLGmlbgwNWmcbwjXEYs4lVCiHlAhDvRx39T/+XslALlwzEH4o9itndL5h234KrhU=
  distributions: sdist bdist_wheel
  skip_existing: true
