version: '3'

services:
  hypothesis_geometry-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/hypothesis_geometry-cpython:8.0.0-alpha
    volumes:
      - ./hypothesis_geometry:/opt/hypothesis_geometry/hypothesis_geometry
      - ./pyproject.toml:/opt/hypothesis_geometry/pyproject.toml
      - ./README.md:/opt/hypothesis_geometry/README.md
      - ./setup.py:/opt/hypothesis_geometry/setup.py
      - ./tests:/opt/hypothesis_geometry/tests
    entrypoint: pytest
