version: '3'

services:
  hypothesis_geometry-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/hypothesis_geometry-cpython:7.1.0-alpha
    volumes:
      - ./hypothesis_geometry:/opt/hypothesis_geometry/hypothesis_geometry
      - ./pytest.ini:/opt/hypothesis_geometry/pytest.ini
      - ./README.md:/opt/hypothesis_geometry/README.md
      - ./requirements-tests.txt:/opt/hypothesis_geometry/requirements-tests.txt
      - ./requirements.txt:/opt/hypothesis_geometry/requirements.txt
      - ./setup.py:/opt/hypothesis_geometry/setup.py
      - ./tests:/opt/hypothesis_geometry/tests
    entrypoint: pytest
