version: '3'

services:
  hypothesis_geometry-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/hypothesis_geometry-cpython:0.2.1
    volumes:
      - ./hypothesis_geometry/:/opt/hypothesis_geometry/hypothesis_geometry/
      - ./tests/:/opt/hypothesis_geometry/tests/
      - ./README.md:/opt/hypothesis_geometry/README.md
      - ./requirements.txt:/opt/hypothesis_geometry/requirements.txt
      - ./requirements-tests.txt:/opt/hypothesis_geometry/requirements-tests.txt
      - ./setup.py:/opt/hypothesis_geometry/setup.py
      - ./pytest.ini:/opt/hypothesis_geometry/pytest.ini
    entrypoint: pytest
