from .base import (concave_contours_sizes_pairs,
                   convex_contours_sizes_pairs,
                   coordinates_strategies,
                   coordinates_strategies_with_limits_and_types,
                   coordinates_strategy_with_limit_and_type_pairs,
                   data,
                   holes_lists_sizes_pairs,
                   invalid_concave_contours_sizes_pairs,
                   invalid_convex_contours_sizes_pairs,
                   invalid_holes_list_sizes_pairs,
                   invalid_polylines_sizes_pairs,
                   non_valid_concave_contours_sizes_pairs,
                   non_valid_convex_contours_sizes_pairs,
                   non_valid_polylines_sizes_pairs,
                   polylines_sizes_pairs)
