from .base import (concave_contours_sizes_pairs,
                   convex_contours_sizes_pairs,
                   coordinates_strategies,
                   coordinates_strategies_with_limits_and_types,
                   coordinates_strategy_with_limit_and_type_pairs,
                   data,
                   invalid_concave_contours_sizes_pairs,
                   invalid_convex_contours_sizes_pairs,
                   invalid_multicontours_sizes_pairs,
                   invalid_multipoints_sizes_pairs,
                   invalid_multipolygons_sizes_pairs,
                   invalid_multisegments_sizes_pairs,
                   multicontours_sizes_pairs,
                   multipoints_sizes_pairs,
                   multipolygons_sizes_pairs,
                   multisegments_sizes_pairs,
                   non_valid_concave_contours_sizes_pairs,
                   non_valid_convex_contours_sizes_pairs)
